name: ML Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      PYTHONUNBUFFERED: 1
      DISABLE_TQDM: 1
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install CPU PyTorch
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-cpu.txt
    
    - name: Install package
      run: |
        pip install -e .
        
    - name: Run tests
      run: |
        python -m unittest discover tests/ -v
        
    - name: Train model
      run: |
        python src/train.py --epochs 20
        
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        retention-days: 90